# Generated by Django 3.2.7 on 2021-10-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('children', 'children'), ('coloring', 'coloring'), ('drawing', 'drawing'), ('cooking', 'cooking')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField()),
            ],
        ),
    ]
